import type { Metadata } from "next";
<<<<<<< HEAD
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Worldlink Cargo Solutions",
  description: "Worldlink Cargo Solutions - Your trusted partner for global shipping and logistics solutions.",
>>>>>>> 231c9eec9d35a9151fdfb9bd7a7de04224e90b2c
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={roboto.variable}>
        {children}
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
>>>>>>> 231c9eec9d35a9151fdfb9bd7a7de04224e90b2c
      </body>
    </html>
  );
}
